const end=new Date();end.setDate(end.getDate()+3);setInterval(()=>{const diff=end-new Date();if(diff<0)return;document.getElementById("days").innerText=Math.floor(diff/(1000*60*60*24));document.getElementById("hours").innerText=Math.floor((diff/(1000*60*60))%24);document.getElementById("minutes").innerText=Math.floor((diff/(1000*60))%60);document.getElementById("seconds").innerText=Math.floor((diff/1000)%60);},1000);
let spots=50;document.getElementById("spots").innerText=spots;const dropSpots=()=>{const delay=30000+Math.floor(Math.random()*30000);setTimeout(()=>{if(spots>3&&Math.random()<0.6){spots--;document.getElementById("spots").innerText=spots;}dropSpots();},delay);};dropSpots();
let shown=sessionStorage.getItem("exit_shown")==="1";function closePopup(){document.getElementById("exitPopup").style.display="none";}
document.addEventListener("mouseout",e=>{if(e.clientY<=5&&!shown){document.getElementById("exitPopup").style.display="flex";shown=true;sessionStorage.setItem("exit_shown","1");}});
let lastScroll=window.scrollY;window.addEventListener("scroll",()=>{if(lastScroll-window.scrollY>120&&!shown){document.getElementById("exitPopup").style.display="flex";shown=true;sessionStorage.setItem("exit_shown","1");}lastScroll=window.scrollY;});
let lastY=Infinity,lastT=0;
document.addEventListener("mousemove",e=>{const y=e.clientY,t=Date.now();const dy=lastY===Infinity?0:lastY-y;const dt=t-lastT;if(!shown&&(y<=10||e.pageY<=10)&&(dy>=2||dt<=1000)){document.getElementById("exitPopup").style.display="flex";shown=true;sessionStorage.setItem("exit_shown","1");}lastY=y;lastT=t;});
document.addEventListener("mouseleave",()=>{if(!shown){document.getElementById("exitPopup").style.display="flex";shown=true;sessionStorage.setItem("exit_shown","1");}});
document.querySelectorAll(".cta").forEach(btn=>{btn.addEventListener("click",e=>{e.preventDefault();const url="https://selar.co/je11414214?add_to_cart=1";const width=900;height=700;const left=(screen.width/2)-(width/2);const top=(screen.height/2)-(height/2);window.open(url,"SelarCheckout",`width=${width},height=${height},top=${top},left=${left},scrollbars=yes`);});});
const video=document.getElementById("vsl");const iframe=document.getElementById("vslFrame");const playBtn=document.querySelector(".play-overlay");const pageDim=document.getElementById("pageDim");
if(playBtn&&iframe&&video){playBtn.addEventListener("click",()=>{document.body.classList.add("immersive");video.classList.add("active");const src=iframe.getAttribute("src")||"";if(!src.includes("autoplay=1")){iframe.src=src+(src.includes("?")?"&":"?")+"autoplay=1";}});}
